[2024-10-25T11:16:48.276+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: check_db_connection.check_connection manual__2024-10-25T11:16:08.397019+00:00 [queued]>
[2024-10-25T11:16:48.286+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: check_db_connection.check_connection manual__2024-10-25T11:16:08.397019+00:00 [queued]>
[2024-10-25T11:16:48.286+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 4
[2024-10-25T11:16:48.299+0000] {taskinstance.py:1382} INFO - Executing <Task(SQLExecuteQueryOperator): check_connection> on 2024-10-25 11:16:08.397019+00:00
[2024-10-25T11:16:48.303+0000] {standard_task_runner.py:57} INFO - Started process 99 to run task
[2024-10-25T11:16:48.306+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'check_db_connection', 'check_connection', 'manual__2024-10-25T11:16:08.397019+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpvomjs6pg']
[2024-10-25T11:16:48.307+0000] {standard_task_runner.py:85} INFO - Job 47: Subtask check_connection
[2024-10-25T11:16:48.351+0000] {task_command.py:416} INFO - Running <TaskInstance: check_db_connection.check_connection manual__2024-10-25T11:16:08.397019+00:00 [running]> on host a6c36815a6df
[2024-10-25T11:16:48.428+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='check_db_connection' AIRFLOW_CTX_TASK_ID='check_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-10-25T11:16:08.397019+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-25T11:16:08.397019+00:00'
[2024-10-25T11:16:48.429+0000] {sql.py:274} INFO - Executing: create table privet (id int);
[2024-10-25T11:16:48.439+0000] {base.py:73} INFO - Using connection ID 'your_postgres_connection_id' for task execution.
[2024-10-25T11:16:48.448+0000] {base.py:73} INFO - Using connection ID 'your_postgres_connection_id' for task execution.
[2024-10-25T11:16:48.452+0000] {sql.py:418} INFO - Running statement: create table privet (id int);, parameters: None
[2024-10-25T11:16:48.453+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DuplicateTable: relation "privet" already exists

[2024-10-25T11:16:48.462+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=check_db_connection, task_id=check_connection, execution_date=20241025T111608, start_date=20241025T111648, end_date=20241025T111648
[2024-10-25T11:16:48.472+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 47 for task check_connection (relation "privet" already exists
; 99)
[2024-10-25T11:16:48.479+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-25T11:16:48.496+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
