[2024-10-27T12:46:05.064+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sql_extract_out.extract manual__2024-10-27T12:46:03.063915+00:00 [queued]>
[2024-10-27T12:46:05.085+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sql_extract_out.extract manual__2024-10-27T12:46:03.063915+00:00 [queued]>
[2024-10-27T12:46:05.086+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-10-27T12:46:05.126+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract> on 2024-10-27 12:46:03.063915+00:00
[2024-10-27T12:46:05.130+0000] {standard_task_runner.py:57} INFO - Started process 11904 to run task
[2024-10-27T12:46:05.137+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sql_extract_out', 'extract', 'manual__2024-10-27T12:46:03.063915+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/DAG_sql.py', '--cfg-path', '/tmp/tmpb8t64ua_']
[2024-10-27T12:46:05.140+0000] {standard_task_runner.py:85} INFO - Job 67: Subtask extract
[2024-10-27T12:46:05.206+0000] {task_command.py:416} INFO - Running <TaskInstance: sql_extract_out.extract manual__2024-10-27T12:46:03.063915+00:00 [running]> on host 0a575922fb59
[2024-10-27T12:46:05.442+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sql_extract_out' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-10-27T12:46:03.063915+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-27T12:46:03.063915+00:00'
[2024-10-27T12:46:05.490+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/DAG_sql.py", line 94, in extract_data
    df.to_csv(f'/opt/airflow/outputfiles/{title}.csv', index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 240, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 737, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 600, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/opt/***/outputfiles'
[2024-10-27T12:46:05.500+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=sql_extract_out, task_id=extract, execution_date=20241027T124603, start_date=20241027T124605, end_date=20241027T124605
[2024-10-27T12:46:05.510+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 67 for task extract (Cannot save file into a non-existent directory: '/opt/***/outputfiles'; 11904)
[2024-10-27T12:46:05.555+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-27T12:46:05.572+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
