[2024-10-27T12:48:33.158+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sql_extract_out.extract manual__2024-10-27T12:48:30.252464+00:00 [queued]>
[2024-10-27T12:48:33.166+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sql_extract_out.extract manual__2024-10-27T12:48:30.252464+00:00 [queued]>
[2024-10-27T12:48:33.166+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-10-27T12:48:33.178+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract> on 2024-10-27 12:48:30.252464+00:00
[2024-10-27T12:48:33.183+0000] {standard_task_runner.py:57} INFO - Started process 66 to run task
[2024-10-27T12:48:33.186+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sql_extract_out', 'extract', 'manual__2024-10-27T12:48:30.252464+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/DAG_sql.py', '--cfg-path', '/tmp/tmpykngszc0']
[2024-10-27T12:48:33.189+0000] {standard_task_runner.py:85} INFO - Job 70: Subtask extract
[2024-10-27T12:48:33.293+0000] {task_command.py:416} INFO - Running <TaskInstance: sql_extract_out.extract manual__2024-10-27T12:48:30.252464+00:00 [running]> on host 9adf08df06f3
[2024-10-27T12:48:33.595+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sql_extract_out' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-10-27T12:48:30.252464+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-27T12:48:30.252464+00:00'
[2024-10-27T12:48:33.941+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/DAG_sql.py", line 94, in extract_data
    df.to_csv(f'/opt/airflow/outputfiles/{title}.csv', index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 240, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: '/opt/airflow/outputfiles/query1.csv'
[2024-10-27T12:48:33.959+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=sql_extract_out, task_id=extract, execution_date=20241027T124830, start_date=20241027T124833, end_date=20241027T124833
[2024-10-27T12:48:33.993+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 70 for task extract ([Errno 13] Permission denied: '/opt/airflow/outputfiles/query1.csv'; 66)
[2024-10-27T12:48:34.042+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-27T12:48:34.062+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
